/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkGreenlineLandscapingRouteImport } from './routes/work/greenline-landscaping'
import { Route as WorkArmstrongAndCoRouteImport } from './routes/work/armstrong-and-co'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGreenlineLandscapingRoute =
  WorkGreenlineLandscapingRouteImport.update({
    id: '/work/greenline-landscaping',
    path: '/work/greenline-landscaping',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkArmstrongAndCoRoute = WorkArmstrongAndCoRouteImport.update({
  id: '/work/armstrong-and-co',
  path: '/work/armstrong-and-co',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/work/armstrong-and-co': typeof WorkArmstrongAndCoRoute
  '/work/greenline-landscaping': typeof WorkGreenlineLandscapingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/work/armstrong-and-co': typeof WorkArmstrongAndCoRoute
  '/work/greenline-landscaping': typeof WorkGreenlineLandscapingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/work/armstrong-and-co': typeof WorkArmstrongAndCoRoute
  '/work/greenline-landscaping': typeof WorkGreenlineLandscapingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/work/armstrong-and-co'
    | '/work/greenline-landscaping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/work/armstrong-and-co'
    | '/work/greenline-landscaping'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/work/armstrong-and-co'
    | '/work/greenline-landscaping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  WorkArmstrongAndCoRoute: typeof WorkArmstrongAndCoRoute
  WorkGreenlineLandscapingRoute: typeof WorkGreenlineLandscapingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/greenline-landscaping': {
      id: '/work/greenline-landscaping'
      path: '/work/greenline-landscaping'
      fullPath: '/work/greenline-landscaping'
      preLoaderRoute: typeof WorkGreenlineLandscapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/armstrong-and-co': {
      id: '/work/armstrong-and-co'
      path: '/work/armstrong-and-co'
      fullPath: '/work/armstrong-and-co'
      preLoaderRoute: typeof WorkArmstrongAndCoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  WorkArmstrongAndCoRoute: WorkArmstrongAndCoRoute,
  WorkGreenlineLandscapingRoute: WorkGreenlineLandscapingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
