/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as WorkApexAutoDetailingRouteImport } from './routes/work/apex-auto-detailing'
import { Route as WorkArmstrongAndCoRouteImport } from './routes/work/armstrong-and-co'
import { Route as WorkGreenlineLandscapingRouteImport } from './routes/work/greenline-landscaping'
import { Route as WorkNorthlineCleaningRouteImport } from './routes/work/northline-cleaning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkApexAutoDetailingRoute = WorkApexAutoDetailingRouteImport.update({
  id: '/work/apex-auto-detailing',
  path: '/work/apex-auto-detailing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkArmstrongAndCoRoute = WorkArmstrongAndCoRouteImport.update({
  id: '/work/armstrong-and-co',
  path: '/work/armstrong-and-co',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGreenlineLandscapingRoute =
  WorkGreenlineLandscapingRouteImport.update({
    id: '/work/greenline-landscaping',
    path: '/work/greenline-landscaping',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkNorthlineCleaningRoute = WorkNorthlineCleaningRouteImport.update({
  id: '/work/northline-cleaning',
  path: '/work/northline-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/work/apex-auto-detailing': typeof WorkApexAutoDetailingRoute
  '/work/armstrong-and-co': typeof WorkArmstrongAndCoRoute
  '/work/greenline-landscaping': typeof WorkGreenlineLandscapingRoute
  '/work/northline-cleaning': typeof WorkNorthlineCleaningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/work/apex-auto-detailing': typeof WorkApexAutoDetailingRoute
  '/work/armstrong-and-co': typeof WorkArmstrongAndCoRoute
  '/work/greenline-landscaping': typeof WorkGreenlineLandscapingRoute
  '/work/northline-cleaning': typeof WorkNorthlineCleaningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/work/apex-auto-detailing': typeof WorkApexAutoDetailingRoute
  '/work/armstrong-and-co': typeof WorkArmstrongAndCoRoute
  '/work/greenline-landscaping': typeof WorkGreenlineLandscapingRoute
  '/work/northline-cleaning': typeof WorkNorthlineCleaningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/get-started'
    | '/how-it-works'
    | '/portfolio'
    | '/pricing'
    | '/work/apex-auto-detailing'
    | '/work/armstrong-and-co'
    | '/work/greenline-landscaping'
    | '/work/northline-cleaning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/get-started'
    | '/how-it-works'
    | '/portfolio'
    | '/pricing'
    | '/work/apex-auto-detailing'
    | '/work/armstrong-and-co'
    | '/work/greenline-landscaping'
    | '/work/northline-cleaning'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/get-started'
    | '/how-it-works'
    | '/portfolio'
    | '/pricing'
    | '/work/apex-auto-detailing'
    | '/work/armstrong-and-co'
    | '/work/greenline-landscaping'
    | '/work/northline-cleaning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GetStartedRoute: typeof GetStartedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  WorkApexAutoDetailingRoute: typeof WorkApexAutoDetailingRoute
  WorkArmstrongAndCoRoute: typeof WorkArmstrongAndCoRoute
  WorkGreenlineLandscapingRoute: typeof WorkGreenlineLandscapingRoute
  WorkNorthlineCleaningRoute: typeof WorkNorthlineCleaningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/apex-auto-detailing': {
      id: '/work/apex-auto-detailing'
      path: '/work/apex-auto-detailing'
      fullPath: '/work/apex-auto-detailing'
      preLoaderRoute: typeof WorkApexAutoDetailingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/armstrong-and-co': {
      id: '/work/armstrong-and-co'
      path: '/work/armstrong-and-co'
      fullPath: '/work/armstrong-and-co'
      preLoaderRoute: typeof WorkArmstrongAndCoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/greenline-landscaping': {
      id: '/work/greenline-landscaping'
      path: '/work/greenline-landscaping'
      fullPath: '/work/greenline-landscaping'
      preLoaderRoute: typeof WorkGreenlineLandscapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/northline-cleaning': {
      id: '/work/northline-cleaning'
      path: '/work/northline-cleaning'
      fullPath: '/work/northline-cleaning'
      preLoaderRoute: typeof WorkNorthlineCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GetStartedRoute: GetStartedRoute,
  HowItWorksRoute: HowItWorksRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  WorkApexAutoDetailingRoute: WorkApexAutoDetailingRoute,
  WorkArmstrongAndCoRoute: WorkArmstrongAndCoRoute,
  WorkGreenlineLandscapingRoute: WorkGreenlineLandscapingRoute,
  WorkNorthlineCleaningRoute: WorkNorthlineCleaningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
